# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78049bd78b9351cb1f2ff769f8523034ab6be135e387997587f78d1ea4d153545112a156a993db5c7f50640bb7001ceaf2160bba2e9fd9c87b3844e236590005

test:
  secret_key_base: 6275cd9bbccdea2f06c95658d35a87894262c718a7ff230ed4ab0c555840bfddbe75a9dbf337232af24b9b6b099339dc3b1407f01db7e3ba44aa812faf46a5db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
