# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ea949a86564b64cade828e5abcfb37c83094005670d26ad62dba4af99b5d432c9e13c5b14fdde555eca863b26e6517fa6f9739774c357f2913f176ccbd84c6

test:
  secret_key_base: 4a0301db4eaf1f3efd79d8940e003f1a90fc340a96f6eb5bc21bd58f3a3808f8ceb0a15842eed0114c390872582dcbaffbe10dacdbe554f6b74388ea0c164301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
