# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_auto_20180221_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
