# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_auto_20180221_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='reviewer.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(max_length=255),
        ),
    ]
