# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db72de67bee9792fafd047f2c476a10d624e1f39c38b539df56c6bb7a26ca654d547b4b4466cda40dfeab2a6523564233b3bb38fd64669096de40dd117f33950

test:
  secret_key_base: 1f27a1174a19913bac09d1483cf33dd5d388d2bd8a31f86b765dc990e1c9ce30f69abef538ad8acfb0808c91d55a45ebea46e206c0a755f576bf25f5933ba445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
