# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c736b7abecb88f86f3ff7c49cef75b0614036eac049b37a9042ecff66b63734290c547bd135cfc90a2867f1359d0edca7f566a6449b630806128b413dd06aab

test:
  secret_key_base: 7233401710bc62d49b0bf057981e20ef27969217afe1a865553404c287974c15a29cdfa748bd7078323b77d6a4f54facc80f6df22a7d7c44fd871a4a9e620031

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
